#!/bin/sh
#
# Safely change the style for FVWM-min. This script just changes a symlink and
# restarts FVWM. However, it does so safely. It can also give help on which
# styles are available, usage information, etc. This should work on any POSIX
# compliant shell.

my_dir=$(dirname "$0")
my_name=$(basename "$0")

print_usage ()
{
	echo "Usage: $my_name STYLE" 1>&2
	echo
	echo 'Styles:'
	echo
	cd "${my_dir}/styles" || return 1
	ls */* | cat
	echo
	return 0
}

main ()
{
	mystyle_path="${my_dir}/mystyle"

	if [ "$#" != 1 ]; then
		print_usage
		return 1
	fi
	if [ -f "$mystyle_path" ] && [ ! -h "$mystyle_path" ]; then
		printf 'Error: "%s" is not a symlink!' "$mystyle_path" 1>&2
		return 1
	fi
	match=$(find "${my_dir}/styles" -name "$1" -type f | sort | head -n 1)
	if [ ! -f "$match" ]; then
		print_usage
		return 1
	fi
	rm -f "$mystyle_path" || return 1
	ln -sf "$match" "$mystyle_path" || return 1
	FvwmCommand Restart 2>/dev/null
	return 0
}

main "$@"
